### PR TITLE
Segmentation and Selectbox Modification

### PR DESCRIPTION
**Pull request by UmutVrl**
Additions: 
Step 6 - second passband selection box
Step 7 - saving segmentations to a new directory

### CODE REVIEW

**Review by dmatthes1982 — CHANGES_REQUESTED** [review]
I would keep it consistent and name the folders of step 7 as follows:  

- 07a_hilbertSegment 
- 07b_plv 
- 07c_mplv

This is not backward compatible, but in consideration of the future extension of the pipeline it makes munch more sense.

**Review by dmatthes1982 — CHANGES_REQUESTED** [review]
File DEEP_main_6:

Please keep the Code consistent and avoid underscores. Change the following names:

passband --> passbandMother
passband_Child --> passbandChild
pbSpec --> pbSpecMother
pbSpec_Child --> pbSpecChild

Later we should log the selected ranges in settings.xls, like we do for other parameters in other DEEP_main_x.m files

**Review by dmatthes1982 — CHANGES_REQUESTED** [review]
File DEEP_main_7:

pbSpec(1:4).winLength should be selectable, otherwise it is not possible to change segmentation size. It's not recommended to change the code of line 77 for different runs of the pipeline.

line 157 is needless

Please note: The current implementation of line 77, may lead to false assumptions. It's highly recommended for PLV estimation that the minimal segment length should cover at least 10 cycles of the  frequency of interest (first approximation: center frequency of passband). That's the reason why a chose segments of 5 seconds for the theta band. Using smaller segments is always not recommended. This has to be considered for the other passbands too.

**Review by dmatthes1982 — CHANGES_REQUESTED** [review]
File DEEP_bpFiltering and DEEP_hilbertPhase:

Please Change bpFreq to bpFreqMother and bpfreq_Child to bpFreqChild and update the documentation (file header)

Please also change data.centerFreq into data.centerFreqMother and the parameter for the Child in a same way

**Review by dmatthes1982 — CHANGES_REQUESTED** [review]
File DEEP_pbSelectbox:

please add the new option boxName to the documentation and at a ft_getopt line for this option like in DEEP_bpFiltering line 29

**Comment by UmutVrl** [comment]
+Step 6 - second passband selection box
+Step 7 - saving segmentations to a new directory
+Consistentcy editing
+DEEP_segSelectbox function

**Comment by UmutVrl** [comment]
+Step 6 - second passband selection box
+Step 7 - saving segmentations to a new directory
+Consistentcy editing
+DEEP_segSelectbox function

**Pull request merged**
